version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-One
    volumes:
      - ./:/app                 # 挂载代码目录（实时同步）
      - ~/.go-cache:/go/pkg/mod # 缓存依赖加速构建
    ports:
      - "8080:8080"             # 应用端口
      - "2345:2345"             # Delve 调试端口
    environment:
      - GOPROXY=https://goproxy.cn,direct
      - AIR_FORCE_COLOR=false  # 强制关闭颜色输出
    command: air -c .air.toml   # 覆盖 CMD（显式指定）
    tty: true
    stdin_open: true    # 保持标准输入开启